In [3]:
# 学习numpy中矩阵操作的代码笔记
import numpy as np

In [7]:
#-------------------矩阵的创建，增删查改，索引，运算-------------------#

#-------------------矩阵的创建，增删查改-------------------#
#创建行向量
x = np.array([1, 2, 3])
print(x)
print(x.shape)
print(type(x))

[1 2 3]
(3,)
<class 'numpy.ndarray'>


In [8]:
# 创建二维与多维矩阵
matrix = np.array([[1, 2, 3], [1, 2, 3], [2, 3 ,4]])
print(matrix)
print(matrix.shape)
print(matrix[0][1])

[[1 2 3]
 [1 2 3]
 [2 3 4]]
(3, 3)
2


In [17]:
## 创建特殊矩阵
# 0矩阵
zeros = np.zeros((2, 2)) # 注意这里有两个小括号
print(zeros)
print(type(zeros[0][0])) # 注意返回的元素为 float

print()
# 1矩阵
ones = np.ones((3, 3))
print(ones)
print(type(ones[0][0]))


[[0. 0.]
 [0. 0.]]
<class 'numpy.float64'>

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.float64'>


In [18]:
# 创建值相同的矩阵
full = np.full((2, 3), 2) # 返回的矩阵元素的类型与给定的元素类型一致
print(full)
print(type(full[0][0]))

print()
full = np.full((2, 3), 2.0)
print(full)
print(type(full[0][0]))

print()
full = np.full((2, 3), False)
print(full)
print(type(full[0][0]))


[[2 2 2]
 [2 2 2]]
<class 'numpy.int32'>

[[2. 2. 2.]
 [2. 2. 2.]]
<class 'numpy.float64'>

[[False False False]
 [False False False]]
<class 'numpy.bool_'>


In [23]:
# 创建对角线为1的矩阵
diag = np.eye(3, 3) # 注意只有一个小括号
print(diag)
print(type(diag[0][0]))

print()
diag = np.eye(2, 3) # 注意如果给定的行列数不等，则只让矩阵中的行列好相等的元素为1
print(diag)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
<class 'numpy.float64'>

[[1. 0. 0.]
 [0. 1. 0.]]


In [39]:
# 创建随机矩阵（值为0-1）
# np.random.seed(1)
random = np.random.random((2, 3)) # 每次运行结果都不一样，要想使得每次运行结果一样，需要在前面加上 np.random.seed(1)
print(random)
print(type(random[0][0]))

[[0.18626021 0.34556073 0.39676747]
 [0.53881673 0.41919451 0.6852195 ]]
<class 'numpy.float64'>


In [46]:
# -----------------矩阵的索引，切片--------------------------#
matrix = np.arange(12).reshape((3, 4))
print(matrix)
print(matrix.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [41]:
# 单个元素的索引
print(matrix[0][0])
print(matrix[0, 0])

0
0


In [42]:
# 切片操作
a = matrix[0:2, 1] # 注意只切片到冒号后面数字的前一位数字，如果缺省数字，则切片全部
print(a)
print(a.shape)

[1 5]
(2,)


In [44]:
# 注意切片后得到的结果维度的变化
a1 = matrix[0:1, :] # 得到的是一个二维矩阵
print(a1)
print(a1.shape)

print()
a2 = matrix[0, :] # 得到的是一个一维的行向量
print(a2)
print(a2.shape)
# 如果想得到一个矩阵需要使用reshape调整维度
print("使用reshape调整维度后：")
a2 = matrix[0, :].reshape((1, -1))
print(a2)
print(a2.shape)

print()
a3 = matrix[0, 0] # 得到的是一个数
print(a3)
print(a3.shape)

[[0 1 2 3]]
(1, 4)

[0 1 2 3]
(4,)
使用reshape调整维度后：
[[0 1 2 3]]
(1, 4)

0
()


In [45]:
# 布尔型矩阵，可以用来索引一些满足条件的元素
matrix = np.arange(9).reshape((3, 3))
print(matrix)
bool_id = matrix > 5 # 对matrix的每个元素进行条件判断，返回布尔矩阵
print(bool_id)
print(matrix[bool_id]) # 根据布尔矩阵提取matrix中的元素，并返回一维向量

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[False False False]
 [False False False]
 [ True  True  True]]
[6 7 8]


In [50]:
# 也可以将上面的代码合并为一行
result = matrix[matrix > 5]
print(result)
print(result.shape)

[ 6  7  8  9 10 11]
(6,)


In [52]:
#---------------------------numpy adarray的数据类型-----------------#
# numpy ndarrray的数据类型是自动识别的，但也可以传入dtype参数进行指定
# 如果输入整型，会给数据定义为int32
matrix1 = np.array([1, 2, 3])
print(matrix1.dtype)
print(type(matrix1[0]))

int32
<class 'numpy.int32'>


In [54]:
# 如果输入的数据为小数点型，则会给数据定义为float64
matrix2 = np.array([1.0, 2.0, 3.0])
print(matrix2.dtype)
print(type(matrix2[0]))

float64
<class 'numpy.float64'>


In [55]:
# 如果同时有整型和浮点型，会将数据类型定义为占字节数多的数据类型
matrix3 = np.array([1.0, 2, 3])
print(matrix3.dtype)
print(type(matrix3[0]))

float64
<class 'numpy.float64'>


In [58]:
# 也可以通过dtype参数指定数据类型
matrix4 = np.array([1, 2, 3], dtype = np.int8)
print(matrix4.dtype)
print(type(matrix4[0]))

int8
<class 'numpy.int8'>


In [60]:
# 当数据本身与指定的数据类型不符合时，会将数据转化为指定的数据类型，生溢出
matrix5 = np.array([1.0, 2.0, 3.0], dtype = np.int32)
print(matrix5)
print(matrix5.dtype)
print(type(matrix5[0]))

[1 2 3]
int32
<class 'numpy.int32'>


In [69]:
# 但是有可能会发生溢出
# 下面的代码指定数据类型为int8，它的数据范围为-128-127，而20000000.0超出了范围，
# 会产生错误数字
matrix6 = np.array([1.0, 20000000.0, 3.0], dtype = np.int8)
print(matrix6)
print(matrix6.dtype)

[1 0 3]
int8


In [72]:
#----------------------矩阵的运算-------------------------#
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [74]:
# 两种加法表示
sum1 = x + y # 直接用加号
sum2 = np.add(x, y) # 使用numpy的函数
print(sum1)
print(sum2)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [76]:
# 两种减法表示
subtract1 = x - y
subtract2 = np.subtract(x, y)
print(subtract1)
print(subtract2)

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [80]:
# 矩阵的对应元素相乘的两种表示
production1 = x *  y
production2 = np.multiply(x, y)
print(production1)
print(production2)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [81]:
# 矩阵的对应元素相除的两种表示
divide1 = x / y
divide2 = np.divide(x, y)
print(divide1)
print(divide2)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [88]:
# 顺便提一下python3的除法返回值类型
# 使用 / 返回float
a = 4 / 2
print(a)
print(type(a))

b = 1.0 / 2.0
print(b)
print(type(b))

2.0
<class 'float'>
0.5
<class 'float'>


In [91]:
# 使用 // 会进行取整操作
a = 1 // 2
print(a)
print(type(a))

b = 1 // 2.0
print(b)
print(type(b))

0
<class 'int'>
0.0
<class 'float'>


In [93]:
# 矩阵的乘法的两种表示
mulDot1 = x.dot(y)
mulDot2 = np.dot(x, y)
print(mulDot1)
print(mulDot2)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [100]:
# 向量的乘法也和矩阵乘法相似
a = np.array([1, 2]) 
b = np.array([3, 4])
print(a.shape)
print(b.shape)
print(a.dot(b))
print(np.dot(a, b))
print(a * b)

(2,)
(2,)
11
11
[3 8]


In [101]:
# 矩阵的基本函数
x = np.array([[1, 2], [3, 4]])
print(x)

[[1 2]
 [3 4]]


In [102]:
# 求和函数
# 对所有元素求和
sum_all = np.sum(x)
print(sum_all)

10


In [103]:
# 对每一列求和，返回一维向量
sum_0 = np.sum(x, 0)
print(sum_0)
print(sum_0.shape)

[4 6]
(2,)


In [104]:
# 对每一行求和，返回一维向量
sum_1 = np.sum(x, 1)
print(sum_1)
print(sum_1.shape)

[3 7]
(2,)


In [105]:
# 矩阵的转置
transform = x.T
print(transform)

[[1 3]
 [2 4]]


In [106]:
# 将一个矩阵或者向量进行维度调整的两种方法
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)
print(x.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [107]:
y = x.reshape((3, 2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


In [108]:
z = np.reshape(x, (3, 2))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [109]:
# 还可以在指定其他维的数值后，将最后一维写作-1，会自动计算这一维的数值
p = x.reshape((3, -1))
print(p)
print(p.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
